### ISSUE TITLE
first::pop marked as causing compile errors actually compiles correctly

### ISSUE THREAD

**Issue by akshat-harit** [rust-unofficial/too-many-lists#100]
I am a novice in rust so not sure of the reasons. Maybe the language had an update? But the following code

```
pub fn pop(&mut self) -> Option<i32> {
    match mem::replace(&mut self.head, Link::Empty) {
        Link::Empty => None,
        Link::More(node) => {
            self.head = node.next;
            Some(node.elem)
        }
    }
```

is listed as causing compilation errors. In particular 
error: use of moved value: `node` [E0382]
src/first.rs:36                 Some(node.elem)

with the solution to use 
```
Link::More(boxed_node) => {
            let node = *boxed_node;
```

However it compiled on my system. I am on Windows machine with the rustc version
rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)

I have also tried on nightly channel and it compiled there as well.

**Comment by Jueast** [comment]
I found a similar problem [here](url). It seems that the reason is [non-lexical lifetimes](https://stackoverflow.com/questions/50251487/what-are-non-lexical-lifetimes)

**Comment by Gankra** [comment]
Seems this was cleaned up a while back
