### ISSUE TITLE
Possible inconsistency in first.rs

### ISSUE THREAD

**Issue by palash25** [rust-unofficial/too-many-lists#101]
Hi, thank you for this project, I am trying to learn rust using this book. Since I am a rust noob I might be wrong here (if I am then sorry for bothering you :sweat_smile: : ) but this was confusing me so I thought I should raise an issue to get some clarification.

In `first.rs` the `push` function definition changes from 

```rust
let new_node = Node {
            elem: elem,
            next: self.head,
        };
```

to 

```rust
let new_node = Box::new(Node {
        elem: elem,
        next: self.head,
    });
```

without any explanation why `Node{}` was changed to `Box::new(Node{})`

**Comment by pty** [comment]
The explanation for using a Box is in 2.1. Layout:

https://cglab.ca/~abeinges/blah/too-many-lists/book/first-layout.html

**Comment by ryancastle** [comment]
I think it's confusing because the part where it changes is in a section that seems to be related to something else i.e. making sure you leave something behind for the owner.
