### ISSUE TITLE
2.5 Pop: Error 0382 "value used after move"

### ISSUE THREAD

**Issue by jeeger** [rust-unofficial/too-many-lists#108]
With `rustc 1.27.0 (3eda71b00 2018-06-19)`, the final "idiomatic" example fails to compile. I found the following solution:

```rust
    pub fn pop(&mut self) -> Option<i32> {
        match mem::replace(&mut self.head, Link::Empty) {
            Link::Empty => None,
            Link::More(node) => {
                let elem = node.elem;
                self.head = node.next;
                Some(elem)
            }
        }
    }
```

However, as I am a Rust beginner, I have no idea how idiomatic this is.

**Comment by jeeger** [comment]
The same occurs in chapter 3.2 when making the list generic, because there needs to be a restriction on the type of T to be copyable. 

Adding 'where T: Copy' was my attempt at fixing this, which suprisingly enough, actually worked ☺.

**Comment by jeeger** [comment]
And in chapter 3.4, this addition is also required.

**Comment by jeeger** [comment]
This also is a duplicate of #100.

**Comment by jeeger** [comment]
Installing nightly cargo and setting `edition = "2018"` in cargo.toml fixed this. Maybe this should be stated in the introduction?

**Comment by Gankro** [comment]
The current version does require Rust 2018, which is 1.31, which has been stable for 4 months.

I should definitely make that more clear, though.

**Comment by jeeger** [comment]
Ah, the problem was that I used an old `cargo` to create the project, thus it didn't use the 2018 edition. With cargo 31, this should be the default though.
