### ISSUE TITLE
Chapter 3.2 Use of moved value error in Rust 1.33

### ISSUE THREAD

**Issue by alastairs** [rust-unofficial/too-many-lists#115]
I've followed through this excellent tutorial to Chapter 3.2 and after converting my functions to support generics, I encounter the following compiler error in the `pop` function:

```plain
error[E0382]: use of moved value: `node`
  --> src\second.rs:29:13
   |
28 |             self.head = node.next;
   |                         --------- value moved here
29 |             node.elem
   |             ^^^^^^^^^ value used here after move
   |
   = note: move occurs because `node.next` has type `std::option::Option<std::boxed::Box<second::Node<T>>>`, which does not implement the `Copy` trait
```

My `pop` function is defined as per the tutorial:

```rust
pub fn pop(&mut self) -> Option<T> {
    self.head.take().map(|node| {
        self.head = node.next;
        node.elem
    })
}
```

I had previously worked around this error by introducing a temporary variable as below, but this technique doesn't work with the generic definition:

```rust
pub fn pop(&mut self) -> Option<i32> {
    self.head.take().map(|node| {
        let result = node.elem;
        self.head = node.next;
        result
    })
}
```

My rust version is `rustc 1.33.0 (2aa4c46cf 2019-02-28)`. Do I need a newer version?

**Comment by Gankro** [comment]
Hmm this is relying on a magic property of box, which I thought was part of rust2018 but now I'm not so sure. Does your cargo.toml contain `edition = "2018"`?

**Comment by alastairs** [comment]
Thanks @Gankro for your reply 😄 This is the contents of my Cargo.toml:

```toml
[package]
name = "lists"
version = "0.1.0"
authors = ["Alastair Smith <email redacted>"]

[dependencies]
```

**Comment by alastairs** [comment]
Adding `edition = "2018"` appears to resolve as you say, thanks for that pointer :+1: I now see this is mentioned in the introduction, so either thanks for updating this, or sorry for missing it 😀

**Comment by Gankro** [comment]
yeah i updated it around the time I posted my comment, good luck!
