### ISSUE TITLE
map_split stable in 1.35

### ISSUE THREAD

**Issue by nico-abram** [rust-unofficial/too-many-lists#131]
There's a mention of map_split in https://rust-unofficial.github.io/too-many-lists/fourth-iteration.html?highlight=map_split#iter .
Now that it's stable in the current release (https://blog.rust-lang.org/2019/05/23/Rust-1.35.0.html) it might be worth it to change the wording there.

**Comment by Gankro** [comment]
It's still new enough that I don't want to assume users have the latest stable build. But yeah I'll keep an eye on it.
