### ISSUE TITLE
cargo test error on rust 1.32.0 and 1.35.0

### ISSUE THREAD

**Issue by nkbai** [rust-unofficial/too-many-lists#133]
rror[E0382]: use of moved value: `node`
  --> src/first.rs:36:22
   |
35 |                 self.head = node.next;
   |                             --------- value moved here
36 |                 Some(node.elem)
   |                      ^^^^^^^^^ value used here after move
   |
   = note: move occurs because `node.next` has type `first::Link`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
error: Could not compile `lists`.

**Comment by nkbai** [comment]
i'm using the latest version 9243ad112f784fe66cb09cd710dc9a7ef5ce552e

**Comment by Gankro** [comment]
Can you confirm that your Cargo.toml has `edition  = "2018"` in it?

**Comment by nkbai** [comment]
@Gankro  thank you very much, it is fixed after I add edtion="2018"

**Comment by Gankro** [comment]
cool 👍
