### ISSUE TITLE
2.5: adding reference for self.head and `ref` keyword in match

### ISSUE THREAD

**Issue by pscott** [rust-unofficial/too-many-lists#138]
The `ref` keyword in the match function gets added at the same time as `&self.head`, in the listing following the sentence : 

"Rust says we should add a reference to our match to fix that. 🤷‍♀️ Let's try it:"

I believe the `ref` keyword is no longer required (or at least the compiler didn't yell at me for not writing it). 

I believe the `ref` keyword in match is now outdated (maybe I misunderstood [this](https://users.rust-lang.org/t/ref-keyword-versus/18818/8)), but if it is not I believe a minimal explanation of this keyword would be very helpful.

As I'm new to Rust, this issue might be completely irrelevant : if it is, please let me know!

**Comment by theSdev** [comment]
Yeah `ref` appeared out of nowhere and it seems it was added afterwards cuz  the following `cargo build` warning messages don't mention the keyword:

```
> cargo build

warning: unused variable: `node`
  --> src/first.rs:32:24
   |
32 |             Link::More(node) => {
   |                        ^^^^ help: consider prefixing with an underscore: `_node`
   |
   = note: #[warn(unused_variables)] on by default

warning: field is never used: `elem`
  --> src/first.rs:13:5
   |
13 |     elem: i32,
   |     ^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: field is never used: `next`
  --> src/first.rs:14:5
   |
14 |     next: Link,
   |     ^^^^^^^^^^
```

**Comment by berquist** [comment]
Using the latest stable (1.46.0), the code doesn't compile with the `ref` present, so it needs to be removed.
