### ISSUE TITLE
second "let new_tail =" shadows first one in push!

### ISSUE THREAD

**Issue by GregDavidson** [rust-unofficial/too-many-lists#142]
In the second version of push in
https://rust-unofficial.github.io/too-many-lists/fifth-layout.html
it is confusing to have two definitions of new_tail, the second shadowing the first
```rust
pub fn push(&mut self, elem: T) {
    // FIRST DEFINITION:
    let new_tail = Box::new(Node {
        elem: elem,
        // When you push onto the tail, your next is always None
        next: None,
    });

    // Put the box in the right place, and then grab a reference to its Node
    // SECOND DEFINITION SHADOWING FIRST ONE
    let new_tail = match self.tail.take() {
        Some(old_tail) => {
            // If the old tail existed, update it to point to the new tail
            old_tail.next = Some(new_tail);
            old_tail.next.as_mut().map(|node| &mut **node)
        }
        None => {
            // Otherwise, update the head to point to it
            self.head = Some(new_tail);
            self.head.as_mut().map(|node| &mut **node)
        }
    };

    self.tail = new_tail;
}
```
Is this a hint that they will wind up having the same value?

**Comment by Gankra** [comment]
This is kinda a standard rust idiom for expressing the same logical value changing type as you refine/compute it. But also it's kinda just confusing here?

**Comment by Kryptos-FR** [comment]
I think it is fine, but adding a sentence in that page would be nice.

Outside of the tests in `third`, I think it is the first time shadowing happens that explicitly in the book.

**Comment by Gankra** [comment]
fifth has been completely rewritten, the old implementation partially remains but it's just there to be a big failed experiment. So I'm fine with it having slop.
