### ISSUE TITLE
First example fails to induce E0072

### ISSUE THREAD

**Issue by MatthijsBlom** [rust-unofficial/too-many-lists#144]
I copied the very first code sample, namely
```rust
pub mod first;

pub enum List {
    Empty,
    Elem(i32, List),
}
```
According to the book, this should prompt the compiler to issue E0072. However, on my machine it builds just fine!

I also tried the example from the [documentation on E0072](https://doc.rust-lang.org/error-index.html#E0072), but got the same behavior, on both Windows and WSL.

What could be causing this?

**Comment by Gankra** [comment]
No idea what's happening for you, but it definitely seems to still not build on nightly: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=f782daa65ed8da173d9e63d0facf6e8b

My only guess is that you're literally not building the file you put that code in?

**Comment by MatthijsBlom** [comment]
Thanks for the hint; I overlooked the instruction to put `pub mod first;` in `src/lib.rs`.
