### ISSUE TITLE
Enum without box compiles

### ISSUE THREAD

**Issue by Genysys** [rust-unofficial/too-many-lists#148]
Trying out the exerices from the book, but confused as to why this builds successfully. 

```
pub enum List{
    Empty,
    Elem(i32, List),
}

```

```
 cargo build
   Compiling lists v0.1.0 (/Users/samueldare/Documents/Code/Rust/linked_list/lists)
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
```

**Comment by PanopticaRising** [comment]
For anyone who stumbles upon this like I did, I forgot to save the addition of the `pub mod first;` import in the main `lib.rs` file.
