### ISSUE TITLE
Inconsistent Chaos Due to Nonlinear Workflows

### ISSUE THREAD

**Issue by Gankro** [rust-unofficial/too-many-lists#15]
I occasionally back-ported some changes to previous chapters, leading to inconsistent or psychic compiler output in some places. In particular tests will appear and disappear in some areas where they shouldn't and should be. Number of tests run is also inconsistent in some places.

Also some final code pages may no longer have the actual final code. Man, it would be great if someone fixed that!

Suuuure would.

**Comment by chirgjn** [comment]
Picking this up :)

**Comment by chirgjn** [comment]
src/third-final.md doesn't use `Arc` is that intended?

**Comment by Gankro** [comment]
It was. We never go over porting the code to Arc, I just felt it was important to mention.

Also, I *believe* I largely fixed this issue in the Rust 2018 update, as for the most part I went through the book in a linear fashion. Anything else is just random typos.

**Comment by chirgjn** [comment]
👍
I was just going through the whole this week, so thought I could help.
Thanks a lot for writing this.
