### ISSUE TITLE
"Not allocated at all" is confusing for some folks

### ISSUE THREAD

**Issue by cellularmitosis** [rust-unofficial/too-many-lists#153]
Early on, the book talks about a node "not being allocated at all": https://rust-unofficial.github.io/too-many-lists/first-layout.html

The book assumes an allocated-always-means-heap-allocated parlance:
- "not allocated at all" implies "stack-allocated"
- "allocated" implies "heap-allocated"

However, some folks were taught using an allocated-means-either-stack-or-heap-allocated parlance:
- "not allocated at all" implies "the object does not exist" (which is nonsensical in this context)
- "allocated" is ambiguous and implies either "stack-allocated" or "heap-allocated"

For folks in the second camp, the book's phrasing is super confusing until they realize a different parlance is being used.

**Comment by Gankra** [comment]
fixed in upcoming release
