### ISSUE TITLE
pre-built prettified version

### ISSUE THREAD

**Issue by Sailsman63** [rust-unofficial/too-many-lists#156]
Would it be possible to have all of the prettified html uploaded as a release zip?

Not everyone is set up/wants to install the tools to build from source, and the markdown is rather more fragmented than is convenient to read raw.

Our only other option is the github.io site, so no offline access.

**Comment by lzutao** [comment]
There a branch: https://github.com/rust-unofficial/too-many-lists/tree/gh-pages

**Comment by Sailsman63** [comment]
Ahh, thank you. I'd forgotten that gh-pages does that...
