### ISSUE TITLE
5.4 Peek Chapter, code not compile ...

### ISSUE THREAD

**Issue by zedongh** [rust-unofficial/too-many-lists#159]
```rust
    pub fn peek_front(&self) -> Option<Ref<T>> {
        self.head.as_ref().map(|node| {
            Ref::map(node.borrow(), |node| &node.elem)
        })
    }
```
> $ cargo build
>   Compiling lists v0.1.0 (/Users/lambda/CLionProjects/lists)
> error[E0308]: mismatched types
>     --> src/fourth.rs:65:22
>       |
> 65 |             Ref::map(node.borrow(), |node| &node.elem)
>       |                      ^^^^^^^^^^^^^ expected struct `std::cell::Ref`, found reference
>       |
>   = note: expected struct `std::cell::Ref<'_, _>`
>           found reference `&_`
>
> error[E0609]: no field `elem` on type `&_`
>  --> src/fourth.rs:65:50
>       |
> 65 |             Ref::map(node.borrow(), |node| &node.elem)
>       |                                                  ^^^^
>
> error: aborting due to 2 previous errors
>
> Some errors have detailed explanations: E0308, E0609.
> For more information about an error, try `rustc --explain E0308`.
> error: could not compile `lists`.

To learn more, run the command again with --verbose.

Here is screenshot.

![截屏2020-04-29下午12 45 54](https://user-images.githubusercontent.com/13192735/80561611-9d876b00-8a17-11ea-8fc9-5893fc5c7b68.png)

**Comment by zedongh** [comment]
I found it seems need call as_ref()
```rust
Ref::map(node.as_ref().borrow(), |node| &node.elem)
```

**Comment by Kryptos-FR** [comment]
It compiles fine if you don't import `Borrow` (`use std::borrow::Borrow`).
