### ISSUE TITLE
Decide on Singly Linked vs Singly-Linked

### ISSUE THREAD

**Issue by Gankro** [rust-unofficial/too-many-lists#16]
I kinda just do whatever I feel like at that precise moment in time. It's 50/50 throughout the text.

**Comment by jonastepe** [comment]
Singly-Linked looks right to me. But in the end, I favour consistency.

**Comment by edunham** [comment]
Flagging as help-wanted; this could be as simple as a regex through the tree to replace all instances of one spelling with the other. 

You, as whoever submits the first PR to fix this issue, get to decide which spelling to standardize on!

**Comment by chirgjn** [comment]
Picking this up :)
