### ISSUE TITLE
Shell command cannot be used directly when using the copy to clipboard button

### ISSUE THREAD

**Issue by robinmoussu** [rust-unofficial/too-many-lists#161]
The first [two commands](https://rust-unofficial.github.io/too-many-lists/) in the introduction contains the symbol `>` to tell that it's a prompt. Unfortunately, this symbol is copied when using the copy to clipboard button.

    ```text
    > cargo new --lib lists
    > cd lists
    ```

I'm not familiar with mdbooks, and highlighjs, so I don't know where to look. I think that the first step would be to replace `text` with `sh` (or `bash` or `zsh`, they are all aliases). Then either remove the `>`, but I think that the display is a bit worse without them, or altering the functionality of the "copy to clipboard" button to first filter out the `>`.

**Comment by Gankra** [comment]
The copy-to-clipboard stuff is auto-generated, I'm fine with it not doing the right thing for terminal sessions.
