### ISSUE TITLE
Suggestion. Demonstrate that iter_mut allows you to mutate the contents of the list

### ISSUE THREAD

**Issue by robotlovesyou** [rust-unofficial/too-many-lists#166]
Since this is an introductory test perhaps it would be useful to have the test for iter_mut demonstrate that the contents of the original list are being mutated, so something like:

```
#[test]
fn iter_mut() {
    let mut list = List::new();
    list.push(1); list.push(2); list.push(3);

    for n in list.iter_mut() {
        *n = *n * *n;
    }
    assert_eq!(list.pop(), Some(9));
    assert_eq!(list.pop(), Some(4));
    assert_eq!(list.pop(), Some(1));
}
```

Happy to try creating a PR if you agree.

**Comment by Gankra** [comment]
A reasonable suggestion but I'd rather not dwell on this too much.
