### ISSUE TITLE
Do you want any more maintainers?

### ISSUE THREAD

**Issue by gilescope** [rust-unofficial/too-many-lists#176]
It looks like the maintainer count is down to one on this repo. Do you want some additional maintinaners so it's not all on one person's sholders?

**Comment by seanchen1991** [comment]
Seconding this. This guide is one of my favorites to recommend for new folks getting into Rust. I definitely think it's one worth updating and maintaining as Rust evolves and improves.

**Comment by gilescope** [comment]
If you submit PRs they are getting merged in given time.

**Comment by Gankra** [comment]
While I appreciate the offer I would much prefer this work be allowed to just Exist as something I made, flawed as it is. Not everything needs to be perfect and eternal.
