### ISSUE TITLE
Suggestion: Note that &T is Copy

### ISSUE THREAD

**Issue by rkrishn7** [rust-unofficial/too-many-lists#177]
Hello,

I think it might be helpful to note that `Option<T>` is `Copy` for `T: Copy`. And that shared references are `Copy`. I was confused at first when reading this because it seemed like we were moving `self.next` out of a shared reference, and rust didn't scream at me. This snippet occurs in section 3.5 (Iter):

```rs
self.next.map(|node| {
    self.next = node.next.map(|node| &node);
    &node.elem
})
```

I think it may be helpful to note this for anyone wondering the same thing!

**Comment by leiter-jakab** [comment]
Hi, this is addressed in chapter 3.6 - IterMut.
