### ISSUE TITLE
Video series based on this tutorial

### ISSUE THREAD

**Issue by pbrkr** [rust-unofficial/too-many-lists#178]
Hi folks, I hope it's ok to open an issue for this as I can't see any other discussion forum for this project.

I'm currently learning Rust and following this tutorial so I decided to capture this process in a video series. Hopefully this is a useful alternative way of presenting the information you've got here and I think it should complement the text you've got here.

Let me know if you have any feedback, objections or encouragement and if there's any additional information you'd like me to give in the videos. I'll close this issue after 2 weeks if there's no feedback.

The first video can be found on YouTube here: https://www.youtube.com/watch?v=aNv_oqveuCE

**Comment by Gankra** [comment]
(Sorry sorry this is cool but I just can't ever find time to watch this, but cool that you did it!)
