### ISSUE TITLE
Fifth: simplified by removing the deref in `pop`

### ISSUE THREAD

**Issue by ChenZhongPu** [rust-unofficial/too-many-lists#207]
The `pop` function in [fifth.rs](https://github.com/rust-unofficial/too-many-lists/blob/master/lists/src/fifth.rs) can be simplified:

```rust
    pub fn pop(&mut self) -> Option<T> {
        self.head.take().map(|head| {
            let head = *head;
            self.head = head.next;

            if self.head.is_none() {
                self.tail = ptr::null_mut();
            }

            head.elem
        })
    }
```

Due to the auto-deref, `let head = *head;` can be removed.

**Comment by Gankra** [comment]
This section has been completely rewritten. Any of the old code is now a large "failed experiment" that leads into the "right" implementation, so I'm fine with it having some slop.
