### ISSUE TITLE
why need mem::replace?

### ISSUE THREAD

**Issue by eclair-lumiere** [rust-unofficial/too-many-lists#212]
In first.rs, chapter drop.

```
impl Drop for List {
  fn drop(&mut self) {
      let mut cur_link = mem::replace(&mut self.head, Link::Empty);

      while let Link::More(mut boxed_node) = cur_link {
          cur_link = mem::replace(&mut boxed_node.next, Link::Empty);
      }
  }
}

```
How about the code below?
```
      while let Link::More(boxed_node) = cur {
          cur = boxed_node.next;
      }
```

The resource was already moved to `boxed_node`, so `boxed_node` is an owner.
I thought it's enough as long as move`boxed_node.next` to cur.

**Comment by Gankra** [comment]
It's just extra verbose because at this point I'm still leaning the developer into a lot of new stuff at once. It's fine.
