### ISSUE TITLE
How to test that Drop trait in first-drop.md avoids memory leaking?

### ISSUE THREAD

**Issue by dennyak47** [rust-unofficial/too-many-lists#214]
I am new to basic programming, and I am very confused about the drop method in first-drop.md.
I tried to remove all the code in the drop function and test it in the nightly chain with [leak sanitizer](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html#leaksanitizer), but the result is that no memory seem to leak even without those codes according to leak sanitizer.
I google a lot of topics and still don't know how to test that "drop code" in first-drop.md acturally works.
Would you please explain how to test this code?

**Comment by Gankra** [comment]
Rust has automatic destructors that are very hard to accidentally leak, so basically anything you do will get all the memory freed unless you use something exotic like `mem::forget`. Blowing the stack is the only real concern.

**Comment by dennyak47** [comment]
Yes, it blows the stack in this test if i delete the code in drop function.

```rust
#[test]
  fn will_not_blow_the_stack() {
    use super::List;
    let mut list: List<i32> = List::new();
    let mut count = 0;
    loop {
      count += 1;
      list.push(4);
      if count > 100000 {
        break;
      }
    }
    drop(list);
    assert_eq!(1, 1);
  }
```
