### ISSUE TITLE
try_unwrap() has been stabilized on nightly

### ISSUE THREAD

**Issue by jonastepe** [rust-unofficial/too-many-lists#24]
`#!feature[rc_unique]` is no longer necessary, since `try_unwrap()` has been stabilized.
This effects the text in
* fourth-breaking.md
* fourth-peek.md

and the source in
* lib.rs

**Comment by Gankro** [comment]
Yay!

**Comment by Gankro** [comment]
It also affects third-drop iirc

**Comment by louy2** [comment]
As I've said in the PR, do we need another intro to nightly in a different place?

**Comment by bestouff** [comment]
Apparently this has been fixed on master. Close bug ?

**Comment by jonastepe** [comment]
lib.rs still contains the ```#![feature(rc_unique,...``` which is no longer necessary either. But otherwise, it looks good to close.

**Comment by bestouff** [comment]
OK. Apply https://github.com/rust-unofficial/too-many-lists/pull/51 then ...
