### ISSUE TITLE
Mutability test for peek_mut on 3.3

### ISSUE THREAD

**Issue by alopatindev** [rust-unofficial/too-many-lists#44]
Thanks for this awesome guide!

I tried to test the mutability of `elem`, accessed with `peek_mut`, like this

```rust
list.peek_mut().map(|&mut elem| {
    elem = 55;
});

assert_eq!(list.peek(), Some(&55));
```

and got `error[E0384]: re-assignment of immutable variable 'elem'` that still doesn't look obvious to me.

After awhile I came up with
```rust
list.peek_mut().map(|mut elem| {
    *elem = 55;
});
```

This (and some explanation) might be helpful to add.

**Comment by jonastepe** [comment]
I have trouble understanding exactly what you want to add to the article. Do you mean an explanation for the code example you provided? Or do you want to add the code example?

**Comment by alopatindev** [comment]
I mean both things: the code example I provided and the explanation of why it doesn't compile.

**Comment by jonastepe** [comment]
I assume you'd want to add it to the test cases of this section. I am not sure whether "some explanation" would suffice here. There's more to how closures destructure their arguments. However, I fear that a more detailed explanation distracts from the main goal of the book. How to implement lists (or, by extension, arbitrary data structures) in Rust.
Maybe you have a better place in mind on where to add this explanation and how it should look like.
