### ISSUE TITLE
Inline Code Formatting

### ISSUE THREAD

**Issue by terrynsun** [rust-unofficial/too-many-lists#45]
This is a silly pet peeve of mine, but I was going through and updating some error messages in the text and I _was_ going to go on a rampage and throw all sorts of things into `inline code format`, but it looks like there's mostly an existing convention:
- Type names that are words (Option, Link, Self) are _usually_ not highlighted (but somewhat inconsistently). Unless it's something like `Option<T>` or `Some(i32)`, which are always highlighted.
- Keywords, variable names are highlighted.
- Trait names (`DerefMut`, `Copy`, `Iter`) are inconsistent?

I would probably just throw all of the above into code highlighting, to avoid unbalanced sentences like

> In the Empty case we need to return None. In the More case we need to return `Some(i32)`

I might be way overthinking this. Do other people have a preference?

**Comment by Manishearth** [comment]
No strong preference.

I often do the "format `Option<T>` but not None" thing just because it gets too distracting if used everywhere. Making the third point about traits consistent sounds like a good thing to do.
