### ISSUE TITLE
Typo in third-basics.md line 60

### ISSUE THREAD

**Issue by Jsbjr** [rust-unofficial/too-many-lists#46]
hi I think there is an error in file [too-many-lists/master/text/third-basics.md](https://github.com/rust-unofficial/too-many-lists/blob/master/text/third-basics.md) line 60
maybe the word **removes** should be replaced with **returns** in order to make more sense. 

`tail` is the logical inverse of this operation. It takes a list and **removes** the
whole list with the first element removed.

**Comment by jonastepe** [comment]
You're right. It does sound better. Do you want to attempt a PR with a fix?

Also, the first code example for ```tail``` is missing the ```as_ref()``` (which is required for this to work) thereby not corresponding to the error message shown.

**Comment by Jsbjr** [comment]
I made a fix in PR #47.

by the way thanks for this  _guided tour_. It is helping me to understand some ideas I didn't grasp while reading the Book.

**Comment by jonastepe** [comment]
Excellent. I think this issue can be closed now.
