### ISSUE TITLE
4.3 Drop Needs rewriting because of try_unwrap becoming stable

### ISSUE THREAD

**Issue by Powersource** [rust-unofficial/too-many-lists#55]
[This commit](https://github.com/rust-unofficial/too-many-lists/commit/294c53f58601183c028c5ae70a92670e379fcfdd) "fixed" it by simply removing all references to unstable. In my opinion, you might as well keep the old version of the text then since the new one doesn't make much sense.

**Comment by Gankra** [comment]
Thanks to whoever did this, but it's done!
