### ISSUE TITLE
Double linked list

### ISSUE THREAD

**Issue by stereobooster** [rust-unofficial/too-many-lists#57]
First of all: thank a lot. I enjoyed reading this manual.

I cheated a bit and googled for "rust double linked list". There is seems to be solution to problem of who is owning who: [stackoverflow](http://stackoverflow.com/questions/22268861/how-would-you-implement-a-bi-directional-linked-list-in-rust).

Second link it to your website e.g. `cglab.ca/~abeinges/blah/too-many-lists/book/`

**Comment by stereobooster** [comment]
I'm thinking about trying to use `Weak` for connection between nodes in one direction and `Rc` in opposite direction. It should remove cycles as far as I understand it.

**Comment by Manishearth** [comment]
Weak lets you implement it safely. I'm not sure what you're proposing? THere already is an impl of a DLL here. There's also one in the stdlib.

**Comment by stereobooster** [comment]
It seems I miss something. Trivial reference counting can't handle cycles. And DLL is the minimum possible cycle (graph of two objects). Right? And `Weak references do not count when determining if the inner value should be dropped.`
