### ISSUE TITLE
Convert from rustbook to mdbook

### ISSUE THREAD

**Issue by edunham** [rust-unofficial/too-many-lists#61]
1) replace the "%" in the first line of each document by a "#"
2) move all the files to a directory "src"
3) create a book.json file with the title etc.
4) add README.md to the SUMMARY.md

see: 

https://github.com/rust-unofficial/too-many-lists/pull/60#issuecomment-257722945

https://github.com/rust-unofficial/too-many-lists/issues/59#issuecomment-254926248

**Comment by kontrafiktion** [comment]
Shall I create a PR?

**Comment by Manishearth** [comment]
Yep!
