### ISSUE TITLE
Pin an mdbook version that compiles

### ISSUE THREAD

**Issue by edunham** [rust-unofficial/too-many-lists#64]
ie https://travis-ci.org/rust-unofficial/too-many-lists/builds/176181181

basically just find a working version and specify it [here](https://github.com/rust-unofficial/too-many-lists/blob/master/.travis.yml#L11)

**Comment by steveklabnik** [comment]
Ouch!

**Comment by kontrafiktion** [comment]
hm, is this still a problem? 
If I read https://github.com/rust-lang/rust/issues/37786 correctly this should now work again

**Comment by edunham** [comment]
Kicked off a rebuild of the master branch at https://travis-ci.org/rust-unofficial/too-many-lists to see whether it's still a problem.

**Comment by kontrafiktion** [comment]
Passed!
