### ISSUE TITLE
Additional Maintainers for this repo

### ISSUE THREAD

**Issue by edunham** [rust-unofficial/too-many-lists#65]
Here's a thread for keeping track of those who'd like to help maintain this repo. 

The duties of a maintainer are to:

* check this repo's issues and PRs once in awhile
* apply the relevant labels to any issues you notice are missing them
* merge PRs that pass their tests and improve the book
* Provide feedback on PRs which fail their tests or which you think would not improve the book
* Follow the spirit of https://www.rust-lang.org/en-US/conduct.html in your role as a maintainer 

If you haven't been invited yet but would like to help out, speak up in this thread!

**Comment by edunham** [comment]
@kontrafiktion, I've noticed that you've been helping out around this repo quite a bit lately. Would you like to be a maintainer as described above?

**Comment by kontrafiktion** [comment]
@edunham I feel honoured by the invite and I like to continue contributing, but I do not have the time to regularly take care of things. I only can help out in "spikes"

**Comment by edunham** [comment]
Please open an issue if you would like to become a maintainer here.
