### ISSUE TITLE
first-push example doesn't compile

### ISSUE THREAD

**Issue by kr** [rust-unofficial/too-many-lists#72]
Hi! I've started working through this tutorial and run into a speed bump:

Everything went fine up until the end of http://cglab.ca/~abeinges/blah/too-many-lists/book/first-push.html, at which point:

```
   Compiling rustlinkedlists v0.1.0 (file:///Users/kr/src/github.com/kr/rustlinkedlists)
error[E0308]: mismatched types
  --> first.rs:29:26
   |
29 | 		self.head = Link::More(new_node);
   | 		                       ^^^^^^^^ expected box, found struct `first::Node`
   |
   = note: expected type `Box<first::Node>`
   = note:    found type `first::Node`

error: aborting due to previous error

error: Could not compile `rustlinkedlists`.

To learn more, run the command again with --verbose.
```

I took a guess and changed the expression to `Link::More(Box::new(new_node))` and that made the error message go away, but I have no idea if that's the right thing to do.

Here's my entire first.rs reproduced exactly below, in case I've made a simple mistake copying it out of the tutorial:

```
use std::mem;

pub struct List {
	head: Link,
}

enum Link {
	Empty,
	More(Box<Node>),
}

struct Node {
	elem: i32,
	next: Link,
}

impl List {
	pub fn new() -> Self {
		List { head : Link::Empty }
	}
}

impl List {
	pub fn push(&mut self, elem: i32) {
		let new_node = Node {
			elem: elem,
			next: mem::replace(&mut self.head, Link::Empty),
		};
		self.head = Link::More(new_node);
	}
}
```

In case it matters, I'm using:

```
:; cargo --version
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
:; rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)
```

**Comment by jzhu98** [comment]
Hi! You're exactly right, `Link::More(Box::new(new_node))` does the job.

The tutorial places the `Box` instantiation in a different place:
```rust
let new_node = Box::new(Node {
    elem: elem,
    next: mem::replace(&mut self.head, Link::Empty),
});
```
but in this case it's equivalent.

**Comment by kr** [comment]
Okay, so that was definitely my mistake! I checked it three times so make sure I was running the same code as in the example and still missed it. 😅 Thanks.
