### ISSUE TITLE
Surprise variable redifinition in 3.2

### ISSUE THREAD

**Issue by PeterShinners** [rust-unofficial/too-many-lists#80]
Section 3.2 has an example of switching the Option match to a map function. It redefines the variable named `node` from box to the unboxed value. I had to reread this line a couple times to be sure it was doing what I thought. 

I think it's worth adding a comment describing this magic just happened, or change the code example to use different variable names. Something like
```rust
pub fn pop(&mut self) -> Option<i32> {
    self.head.take().map(|box_node| {
        let node = *box_node;
        self.head = node.next;
        node.elem
    })
}
```

**Comment by Gankro** [comment]
this is a pretty common idiom that rust programmers should be expected to get used to (although it's not without controversy), but yeah noting this would be a good idea.
