### ISSUE TITLE
Ch2 Drop Box<Node>

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [rust-unofficial/too-many-lists#88]
I'm getting two compile errors when implementing `Drop` for `Box<Node>`
- error[E0425]: cannot find function `deallocate` in this scope
- error[E0119]: conflicting implementations of trait `std::ops::Drop` for type `std::boxed::Box<first::Node>`

```rust
impl Drop for Box<Node> {
    fn drop(&mut self) {
      self.ptr.drop();
      deallocate(self.ptr);
    }
}
```

```bash
   Compiling lists v0.1.0 (file:///Users/williamrusnack/Documents/rust_practice/too_many_lists/lists)
error[E0425]: cannot find function `deallocate` in this scope
  --> src/first.rs:64:7
   |
64 |       deallocate(self.ptr);
   |       ^^^^^^^^^^ not found in this scope

error[E0119]: conflicting implementations of trait `std::ops::Drop` for type `std::boxed::Box<first::Node>`:
  --> src/first.rs:61:1
   |
61 | / impl Drop for Box<Node> {
62 | |     fn drop(&mut self) {
63 | |       self.ptr.drop();
64 | |       deallocate(self.ptr);
65 | |     }
66 | | }
   | |_^
   |
   = note: conflicting implementation in crate `alloc`:
           - impl<T> std::ops::Drop for std::boxed::Box<T>
             where T: ?Sized;

error: aborting due to 2 previous errors

error: Could not compile `lists`.

To learn more, run the command again with --verbose.
```

cargo 0.24.0 (45043115c 2017-12-05)
rustc 1.23.0 (766bd11c8 2018-01-01)

**Comment by BebeSparkelSparkel** [comment]
Looking further into this:  
Unstable: the precise API and guarantees it provides may be tweaked slightly, especially to possibly take into account the types being stored to make room for a future tracing garbage collector  

From: https://doc.rust-lang.org/1.3.0/std/rt/heap/index.html

**Comment by Manishearth** [comment]
That's example code of what not to do, it's not actually supposed to work.

**Comment by Manishearth** [comment]
This is an expanded version of "what the compiler would do when it implements Drop". It's more like pseudocode; not expected to compile.

**Comment by BebeSparkelSparkel** [comment]
I saw the note below:
```rust
        // NOTE: you can't actually explicitly call `drop` in real Rust code;
        // we're pretending to be the compiler!
```
But, then at the bottom it says that the code actually compiled:
```bash
> cargo test
   Compiling lists v0.1.0 (file:///Users/ABeingessner/dev/too-many-lists/lists)
     Running target/debug/lists-5c71138492ad4b4a

running 1 test
test first::test::basics ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests lists

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```
Showing a good compile makes it seem like the code should actually compile.
