### ISSUE TITLE
[question] What is &**node (in Iter)?

### ISSUE THREAD

**Issue by karel-3d** [rust-unofficial/too-many-lists#92]
I am not sure if it is OK to ask stupid questions here. I now feel like a student in a lecture that nods along the way and feels like he understand, until suddenly he doesn't.

I am not sure what does this line mean.

`self.next = node.next.as_ref().map(|node| &**node);`

Especially the end - `&**node`.

Why do I need to de-reference node twice and then reference again? `*` and `&` should be inverse functions, so instead of `&**node` we could write just `*node`, no?

I am obviously missing something, because I obviously cannot. I am not sure why not. :)

**Comment by Manishearth** [comment]
`*` also derefs things like `Box<T>` and `Rc<T>`, it's more general than the inverse of `&`.

If you want to get an `&T` out of an `Rc<T>`, you write `&*rc`. In _many_ cases `&rc` will coerce to what you want, but not all of them, and in those you see `&*`-like things

**Comment by karel-3d** [comment]
Thanks!

Also thanks for the book, if that wasn't implicit.
