### ISSUE TITLE
it assumes cargo new makes a lib but it makes a bin

### ISSUE THREAD

**Issue by robinderksen** [rust-unofficial/too-many-lists#93]
On the first page, the first instructions are 
cargo new lists
cd lists

cargo new by default makes a bin, not a lib. The beginning of chapter 2 seems to indicate a lib was expected here. 

I propose to change the above code in chapter 1 to include --lib

**Comment by mbudde** [comment]
This has already been fixed in #91 but the website is still on an old version apparently. @Gankro could you upload a new version?

**Comment by Gankro** [comment]
@edunham is the one with deploy perms

**Comment by siddharthasahu** [comment]
Another ping. It'd be good to update the website to handle Rust 2018. Thanks!

**Comment by Manishearth** [comment]
Should we just rehost to rust-unofficial.github.io?

**Comment by Gankro** [comment]
I don't know enough about our infra to say what should be done with this.

**Comment by siddharthasahu** [comment]
Looks like https://rust-unofficial.github.io/too-many-lists is already working via Travis. Maybe the old one can just be redirected to this for now?

**Comment by siddharthasahu** [comment]
I think this issue can be closed now?

**Comment by Gankro** [comment]
I was leaving this open as a reminder to setup redirects, but yeah i finally got that done.

**Comment by siddharthasahu** [comment]
Yeah, I did check that the redirects were working :)
