### ISSUE TITLE
Broken link in Introduction 

### ISSUE THREAD

**Issue by thvdburgt** [rust-unofficial/too-many-lists#94]
The following link in the introduction (README.md) is broken (404):
[slices]: https://doc.rust-lang.org/book/slice-patterns.html

**Comment by radiofreejohn** [comment]
I found a versioned copy here: https://doc.rust-lang.org/1.15.1/book/slice-patterns.html

**Comment by Gankra** [comment]
This was fixed a while back, but the next revision is going to rework this section regardless.  Slice patterns were an unstable feature that got simplified when they got stabilized.

https://doc.rust-lang.org/edition-guide/rust-2018/slice-patterns.html
