### ISSUE TITLE
spelling error: "coallesces" should be "coalesces"

### ISSUE THREAD

**Issue by weiss-uni-lib-trier** [rust-unofficial/too-many-lists#99]
Thankyou for this amazing learning resource!

The text kept me entertained and I learned so much about rust ^^

Now lets move to the serious matter: *The Error Report*
Chapter 3.4 spelling error: "coallesces" should be "coalesces" (https://dict.leo.org/englisch-deutsch/coalesce)

**Comment by chirgjn** [comment]
This seems to be fixed now :)
